# vim:set ft=dockerfile:

# VERSION 1.0
# AUTHOR:         Thomas Browet (tbrowet@tbrexpertise.be)
# DESCRIPTION:    Run sslscan in a docker container
# TO_BUILD:       docker build --rm -t tbrowet/docker-sslscan .
# SOURCE:         https://github.com/tbrowet/sslscan

# Pull base image.
FROM ubuntu:16.04
MAINTAINER Thomas Browet "tbrowet@tbrexpertise.be"

RUN \
  apt-get update && \
  apt-get install -y build-essential git zlib1g-dev && \
  git clone https://github.com/rbsec/sslscan.git && \
  cd sslscan && \
  make static && \
  make install && \
  cd / && \
  rm -rf /sslscan && \
  apt-get purge -y git build-essential && \
  apt-get -y autoremove --purge && \
  rm -rf /var/lib/apt/lists/*

RUN \
  export uid=1000 gid=1000 && \
  groupadd --gid ${gid} user && \
  useradd --uid ${uid} --gid ${gid} --create-home user

USER user
WORKDIR /home/user

ENTRYPOINT ["/usr/bin/sslscan"]